config/routes.rb
Rails.application.routes.draw do
  # top画面を/のルートに設定
  root to: 'homes#top'
  # aboutのルート作成
  get "home/about" => "homes#about"

  devise_for :users

  resources :books, only: [:create, :edit, :index, :show, :update, :destroy]
  resources :users, only: [:create, :edit, :index, :show, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: 'You have created book successfully'
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def edit
      @book = Book.find(params[:id])

      @user = @book.user

      if current_user == @book.user
        render action: :edit
      else
        redirect_to books_path
      end
  end

  def index
    @books = Book.all
    @book = Book.new
    @book.user_id = current_user.id
  end

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @user = @book.user
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: 'You have updated book successfully'
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_list.html.erb
<h2>User info</h2>

  <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>

  <table class="table">
    <tbody><tr></tr>
      <tr>
	      <th>name</th>
	      <th><%= user.name %></th>
      </tr>

      <tr>
	      <th>introduction</th>
	      <th><%= user.introduction %></th>
      </tr>
    </tbody>
  </table>

app/views/books/edit.html.erb
<p id="notice"></p>

<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>

		  <% if @book.errors.any? %>
        <%= @book.errors.count %>error prohibited this book from being saved:<br>
        <% @book.errors.full_messages.each do |message| %>
          <%= message %>
        <% end %>
      <% end %>

      <%= form_with model:@book, local:true do |f| %>
        <div class = "form-group">
          <label for = "book_title">Title</label>
          <%= f.text_field :title, class: "form-control" %>
        </div>

        <div class = "form-group">
          <label for = "book_option">Option</label>
          <%= f.text_area :body, class: "form-control"%>
        </div>

        <div class = "form-group">
          <%= f.submit 'Update Book', class: "btn btn-success"%>
        </div>

      <% end %>

      <%= link_to "Show", book_path(@book.id) %>
      |<%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<p id="notice"></p>

<div class="container px-5 px-sm-0">

  <% if @book.errors.any? %>
    <%= @book.errors.count %>error prohibited this book from being saved:<br>
    <% @book.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
  <% end %>

  <div class="row">
    <div class="col-md-3">
    <%= render 'books/list', user: current_user %>

    <div class="row">
      <%= link_to "", edit_user_path(current_user.id), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
    </div>

    <h2 class="mt-3">New book</h2>

    <%= form_with model:@book, url:'/books', class: 'new_book', id: 'new_book', local:true do |f| %>
      <div class = "form-group">
        <label for = "book_title">Title</label>
        <%= f.text_field :title, class: "form-control" %>
      </div>

      <div class = "form-group">
        <label for = "book_option">Option</label>
        <%= f.text_area :body, class: "form-control" %>
      </div>

      <div class = "form-group">
        <%= f.submit 'Create Book', class: "btn btn-success" %>
      </div>

    <% end %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>

      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @books.each do |book| %>

            <tr>
              <td> <%= link_to user_path(book.user) do %>
              <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40' %>
              <% end %>
              </td>

              <td style="white-space: normal;"><%= link_to book_path(book.id) do %>
              <%= book.title %>
              <% end %>
              </td>

              <td style="white-space: normal;"><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>

      </table>
    </div>

  </div>
</div>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <% if @book.errors.any? %>
    <%= @book.errors.count %>error prohibited this book from being saved:<br>
    <% @book.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
  <% end %>

  <div class="row">
    <div class="col-md-3">
    <%= render 'books/list', user: @user %>

    <div class="row">
      <%= link_to "", edit_user_path(@user.id), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
    </div>

    <h2 class="mt-3">New book</h2>

    <%= form_with model:@book_new, url:'/books', class: 'new_book', id: 'new_book', local:true do |f| %>
      <div class = "form-group">
        <label for = "book_title">Title</label>
        <%= f.text_field :title, class: "form-control" %>
      </div>

      <div class = "form-group">
        <label for = "book_option">Option</label>
        <%= f.text_area :body, class: "form-control" %>
      </div>

      <div class = "form-group">
        <%= f.submit 'Create Book', class: "btn btn-success" %>
      </div>

    <% end %>
    </div>

    <div class="col-md-8 offset-md-1">
  		<h2>Book detail</h2>

  		<table class="table">
  		  <tbody>
            <tr>
              <td> <%= link_to user_path(@book.user) do %>
              <%= attachment_image_tag @book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40' %>
              <br><%= @book.user.name %>
              <% end %>
              </td>

              <td style="white-space: normal;"><%= link_to book_path(@book.id) do %>
              <%= @book.title %>
              <% end %>
              </td>

              <td style="white-space: normal;"><%= @book.body %></td>

              <% if current_user.id == @book.user.id  %>
                <td><%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-sm btn-success" %></td>

                <td><%= link_to "Destroy", book_path(@book.id), class: "btn btn-sm btn-danger", method: :delete, data: { confirm: '本当に消しますか？' } %></td>
              <% else %>
              <% end %>
            </tr>

        </tbody>
      </table>
    </div>
  </div>
</div>